#!/bin/sh

# this is a script which is executed after disconnecting the ppp interface.
# look at man pppd for details

# the followings parameters are available:
# $1 = interface-name
# $2 = tty-device
# $3 = speed
# $4 = local-IP-address
# $5 = remote-IP-address
# $6 = ipparam

# Where to store a status flag-files
STATUSDIR=/etc/ppp/status
RM=/bin/rm
EXTIF="195.210.145.4"
IPTABLES=/sbin/iptables
NATRULE="${IPTABLES} -t nat -D POSTROUTING -o eth0 -s $5 -j SNAT --to-source ${EXTIF}"
REALRULE="${IPTABLES}"

if [ `echo $5|egrep '^10\.|^192\.168\.|^172\.16\.'` ]; then
        `${NATRULE}`
fi

# rm flag-file
${RM} -f ${STATUSDIR}/${PEERNAME}
