#!/bin/sh

# this is a script which is executed after connecting the ppp interface.
# look at man pppd for details

# the followings parameters are available:
# $1 = interface-name
# $2 = tty-device
# $3 = speed
# $4 = local-IP-address
# $5 = remote-IP-address
# $6 = ipparam

# Strings
STATUSDIR=/etc/ppp/status
STATUSFILE=${STATUSDIR}/${PEERNAME}
TOUCH=/bin/touch
KILL=/bin/kill
EXTIF="195.210.145.4"
IPTABLES=/sbin/iptables
NATRULE="${IPTABLES} -t nat -A POSTROUTING -o eth0 -s $5 -j SNAT --to-source ${EXTIF}"
REALRULE="${IPTABLES}"

if [ `echo $5|egrep '^10\.|^192\.168\.|^172\.16\.'` ]; then
	`${NATRULE}`
	echo $5 >> ${STATUSFILE}
fi

# Touch a flag-file
${TOUCH} ${STATUSFILE}
