#!/bin/bash
#
# Update script for Gentoo written
# by Stian B. Barmen (stian@barmen.nu)
#

# Modify to you're preferred log file location.
log=/root/update.log

# Portage's color scheme is not perferred in log files and mails.
export NOCOLOR="true"

echo >> "$log"
echo
echo "== Updating `hostname` on `date` ==" >> "$log"
echo "== Updating `hostname` on `date` =="
echo
echo "== Syncing Portage ==" >> "$log"
echo "== Syncing Portage =="
emerge sync &> /dev/null

echo "== Calculating Updates ==" >> "$log"
echo "== Calculating Updates =="

update=`emerge -up world |grep ebuild`

# If we have updates move to install, if not move to check
# config files.
if [ "$update" == '' ]
then
   echo "== No new updates available ==" >> "$log"
   echo "== No new updates available =="
else
   echo "$update"
   echo "== Updating ==" >> "$log"
   echo "== Updating =="
   emerge --update world &> /dev/null


      update=`emerge -up world |grep ebuild`

        if [ "$update" == '' ]
        then
               echo "== All Updates Installed Sucessfully ==" >> "$log"
               echo "== All Updates Installed Sucessfully =="
            else
           echo "== Updates still not Installed ==" >> "$log"
           echo "== Updates still not Installed =="
           echo $updates >> "$log"
           echo $updates
        fi
fi

# Any config files for etc-update to update?
config_files=`find /etc -iname '._cfg*'`

if [ "$config_files" == '' ]
then
    echo "== All config files updated ==" >> "$log"
    echo "== All config files updated =="
else
    echo "== Config files needs updating: ==" >> "$log"
    echo "== Config files needs updating: =="
    echo $config_files >> "$log"
    echo $config_files
    echo "== Use etc-update to update the config now! =="
fi

eix_update=`update-eix | grep -i database`
echo "== Eix Database Updated Successfuly ==" >> "$log"
echo "== Eix Database Updated Successfuly =="
echo $eix_update >> "$log"
echo $eix_update

echo
echo "== Gentoo Update Complete on `date` ==" >> "$log"
echo "== Gentoo Update Complete on `date` ==" 

