application: onlinegtd
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
  
- url: /img
  static_dir: img
  
- url: /js
  static_dir: js
  
- url: /a/.*
  script: gtd.py
  login: required
  
- url: /admin/.*
  script: admin.py
  login: admin
  
- url: .*
  script: main.py
