#!/bin/bash

SQUID_LOG=/var/log/squid/access.log
LOG_DIR=/var/www/awstats

grep "forum.netcom-r.ru" $SQUID_LOG > $LOG_DIR/172.16.0.1/access.log && \
/usr/share/webapps/awstats/6.5/hostroot/cgi-bin/awstats.pl -config=172.16.0.1 -update 2>&1 > /dev/null

grep "largos.ru" $SQUID_LOG > $LOG_DIR/172.16.0.2/access.log && \
/usr/share/webapps/awstats/6.5/hostroot/cgi-bin/awstats.pl -config=172.16.0.2 -update 2>&1 > /dev/null

grep "vaidena.by" $SQUID_LOG > $LOG_DIR/172.16.0.3/access.log && \
/usr/share/webapps/awstats/6.5/hostroot/cgi-bin/awstats.pl -config=172.16.0.3 -update 2>&1 > /dev/null

grep "westside.ru\|west-side.ru" $SQUID_LOG > $LOG_DIR/172.16.0.4/access.log && \
/usr/share/webapps/awstats/6.5/hostroot/cgi-bin/awstats.pl -config=172.16.0.4 -update 2>&1 > /dev/null

grep "chat.netcom-r.ru" $SQUID_LOG > $LOG_DIR/172.16.0.5/access.log && \
/usr/share/webapps/awstats/6.5/hostroot/cgi-bin/awstats.pl -config=172.16.0.5 -update 2>&1 > /dev/null

grep "www.rubin.ru\|http:\/\/rubin.ru" $SQUID_LOG > $LOG_DIR/172.16.0.6/access.log && \
/usr/share/webapps/awstats/6.5/hostroot/cgi-bin/awstats.pl -config=172.16.0.6 -update 2>&1 > /dev/null

grep "jurstrana.ru" $SQUID_LOG > $LOG_DIR/172.16.0.7/access.log && \
/usr/share/webapps/awstats/6.5/hostroot/cgi-bin/awstats.pl -config=172.16.0.7 -update 2>&1 > /dev/null

grep "forum.rubi.ru" $SQUID_LOG > $LOG_DIR/172.16.0.8/access.log && \
/usr/share/webapps/awstats/6.5/hostroot/cgi-bin/awstats.pl -config=172.16.0.8 -update 2>&1 > /dev/null

grep "press.gorbushkin.ru" $SQUID_LOG > $LOG_DIR/172.16.0.9/access.log && \
/usr/share/webapps/awstats/6.5/hostroot/cgi-bin/awstats.pl -config=172.16.0.9 -update 2>&1 > /dev/null

grep "http:\/\/rubi.ru\|www.rubi.ru\|http:\/\/gorbushkin\|www.gorbushkin\|http:\/\/ruby.ru\|www.ruby.ru\|shop.rubi.ru" $SQUID_LOG > $LOG_DIR/172.16.0.10/access.log && \
/usr/share/webapps/awstats/6.5/hostroot/cgi-bin/awstats.pl -config=172.16.0.10 -update 2>&1 > /dev/null

grep "my-monica.com" $SQUID_LOG > $LOG_DIR/172.16.0.11/access.log && \
/usr/share/webapps/awstats/6.5/hostroot/cgi-bin/awstats.pl -config=172.16.0.11 -update 2>&1 > /dev/null
